### ISSUE TITLE
sing-shadowtls v3 lossy 模式的 TLS 1.2 client 连接问题

### ISSUE THREAD

**Issue by WriteMemory** [SagerNet/sing-shadowtls#1]
报错：inbound/socks[socks5-in]: process connection from xxx.xx.xxx.xx:49877: traffic hijacked or TLS1.3 is not supported

当server禁用v3的严格模式时（采用 lossy 模式），sing-shadowtls 的 client 端无法使用 TLS 1.2 模式连接。
采用 shadow-tls 的 client 没有这个问题。

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-shadowtls/commit/ebadc7615da37b1998ec9f013741a1e5fe46472d
